### ISSUE TITLE
Support class methods as tombstone functions

### ISSUE THREAD

**Issue by lyudmild** [scheb/tombstone#17]
As noted in the documentation you need to include the file defining the tombstone function as early as possible. In larger projects which don't have a single entry point this presents a greater possibility to run into "Call to undefined function" errors. Supporting class instance or static methods will alleviate the issue by relying on the dynamic class autoloader.

**Comment by scheb** [comment]
Why not loading the function when you're loading the autoloader?

**Comment by lyudmild** [comment]
That's an option but as I mentioned the complexity of the project is pretty high. I am dealing with a monolithic codebase backing up several websites, having multiple autoloaders. I have also implemented my own tombstone function, relying on other custom classes so there is a higher risk of missing something and breaking things. That said, I understand that this is probably a unique use case which doesn't warrant the extension of the library. However are there any technical limitations which prevent adding this? From my understanding it comes down to extending the [TombstoneNodeVisitor](https://github.com/scheb/tombstone/blob/3c907a20eee70f6593e176ec9c2dcc0841538adb/src/analyzer/Stock/TombstoneNodeVisitor.php). Thank you!

**Comment by scheb** [comment]
Ok, I see.

I remember that I was working on this during v1.0 development, but I don't remember why it eventually didn't make it into the release, if there was maybe a good reason why I didn't do it.

Overall, if there isn't any blocker that I don't know about yet, I'd be happy to accept a PR for this feature.

**Comment by lyudmild** [comment]
Thank you! I have submitted a PR.

**Comment by scheb** [comment]
Released as v1.4.0
