### ISSUE TITLE
Remove sebastian/finder-facade dependency

### ISSUE THREAD

**Issue by scheb** [scheb/tombstone#19]
The tombstone package depends on `sebastian/finder-facade`, which is nowadays abandoned and the 2.0 version is not compatible with 8.0. We should migrate to a replacement, likely directly using `symfony/finder` (instead of using it through the facade) would be the best choice.

If someone wants to pick this up, feel free propose a solution.

**Comment by swarrenwecareconnectorg** [comment]
Thank you for maintaining this project.  It's been a big help in our cleanup project.

I need PHP 8 support so I'm willing to rewrite this.  How would you like me to do that?  It looks like the best option would be to create a FinderFacade that has the same structure as the one Sebastian made.

**Comment by scheb** [comment]
Sounds like a good plan 👍 In that case, the facade class could also be simplified, to support only the things that are needed.
