### ISSUE TITLE
HTML report with wrong bootstrap version

### ISSUE THREAD

**Issue by wprigollopes** [scheb/tombstone#22]
**Package version**: 1.5.0

**Description**

When we try to generate HTML report output we have an unformatted document.

Checking the CSS files, we can see that the minified bootstrap is in version 4.5.2, and inside HTML report templates we are trying to link version 4.1.3, which tries to load a different version and break the beautiful output. May the best option is remove the version from HTML files.

**To Reproduce**

Generate a `tombstone-analyzer` output with the `html` option and try to see the results.

**Additional Context**

One HTML template:
https://github.com/scheb/tombstone/blob/1.x/src/analyzer/Report/Html/Template/dashboard.html.dist#L7

Bootstrap version on CSS folder:
https://github.com/scheb/tombstone/blob/1.x/src/analyzer/Report/Html/Template/css/bootstrap.min.css#L2

**Comment by scheb** [comment]
The query parameter shouldn't be a problem, because in the end it's just a query parameter and that doesn't prevent the CSS file from loading. Your loading issue must originate from something else.

Was there any CSS file generated in the output? 
Would you please check which URL it's trying to load it from, and how does that URL differ from the place where the CSS file is actually located?

**Comment by wprigollopes** [comment]
is located on `/tombstones/reports/html` folder.

If I just remove the version using developer tools, the CSS layout works very well.

With original code, this is the result:
![Screen Shot 2022-07-11 at 5 20 54 PM](https://user-images.githubusercontent.com/8663950/178352044-60f5643d-f220-4a78-bce5-ecff84e571a2.png)

Just removing the version, the result page presents awesome:
![Screen Shot 2022-07-11 at 5 26 56 PM](https://user-images.githubusercontent.com/8663950/178352658-dfef66e5-4b32-4761-bd17-d80a11874cad.png)

**Comment by scheb** [comment]
Never seen before that a query parameter is causing such trouble. But key, no problem with removing this thing from the URL. Thanks for the PR. Merged and released under 1.5.1.
