### ISSUE TITLE
Dependency Conflict Issue

### ISSUE THREAD

**Issue by JimTools** [scheb/tombstone#30]
**Package version**: 1.5.2

**Description**
There is an interesting consequence of using the `phpunit/php-text-template` when a project already has PHPUnit installed which is almost certain. you will only get the newer packages with PHP version <7.4 due to a conflict with PHPUnit version of `phpunit/php-text-template` it wants v3. 

- PHP <7.4, Package: 1.5.2
- PHP 7.4, Package: 0.19.0
- PHP 8+, Package: 0.8.0

**To Reproduce**
1. copy example `composer.json` into an empty directory
2. run composer install
3. run `composer require scheb/tombstone`
4. read the output of the installed version.

**Additional Context**
composer.json
```json
{
    "name": "dependecy/issue",
    "type": "project",  
    "license": "MIT",
    "require": {
        "php": "~8.0"
    },
    "config": {
        "platform": {
            "php": "8.0"
        }
    },
    "require-dev": {
        "phpunit/phpunit": "^7.0|^8.0|^9.5|^10.5|^11.0"
    }
}

```
Output
```
./composer.json has been updated
Running composer update scheb/tombstone
Loading composer repositories with package information
Updating dependencies
Lock file operations: 2 installs, 0 updates, 0 removals
  - Locking psr/log (1.1.4)
  - Locking scheb/tombstone (0.8.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing psr/log (1.1.4): Extracting archive
  - Installing scheb/tombstone (0.8.0): Extracting archive
1 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
25 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
No security vulnerability advisories found.
Using version ^0.8.0 for scheb/tombstone
```

**Comment by JimTools** [comment]
this explains why it was slightly painful getting this to work initially 😅

**Comment by scheb** [comment]
First, let me clear this is not a bug, it's standard behavior by the package manager. If you do a `composer require scheb/tombstone` you say "give me any scheb/tombstone version that you can find to be working within my existing version constraints". There is no guarantee to get the latest version. If you want the latest version, you have to tell Composer the version constraint that you want.

The reason why you get v0.8.0 of the package is `phpunit/php-text-template: ^1.2.1|^2.0` being declared as a dependency. If you have PHPUnit already installed with a newer version of `phpunit/php-text-template`, then the package manager will look for a version that is compatible with this requirement. And that's likely going to be one of the older versions, which do not have a dependency on `phpunit/php-text-template` at all.

The way out of this misery is likely to bump up the version constraints on the package dependencies to newer package versions. But I have my doubts that supporting a version range from PHP7.1-compatible to PHP8.3-compatible dependencies is going to work. Likely would need to ditch PHP7 and release a new major version that supports the range of PHP8 versions.

**Comment by JimTools** [comment]
I’ve not had a chance to looking into the differences between different versions and if it can just be added (I doubt it)

but ill like to try! 

I think there is value in keeping as many versions of PHP supported as possible as just because a project is on the latest version doesn’t mean it’s well maintained or free of dead code.

If it’s not possible at least documenting the behavior so people are aware.

What are your thoughts?
