### ISSUE TITLE
StackTraceFrame->getLine returns the last line on multi-line method calls

### ISSUE THREAD

**Issue by carlosas-cmp** [scheb/tombstone#4]
When retrieving the line information of a StackTraceFrame where the call of the frame is something like:
```
$object->someMethod(
  $argumentOne,
  $argumentTwo,
  $argumentThree,
);
```
inside each of the StackTraceFrames of the generated Vampire, the method `getLine()` shows the line of the last argument (4) instead of the line where the method name is (1).

Shouldn't it be the other way around?

**Comment by scheb** [comment]
Data is coming from `(new \Exception())->getTrace()`. I've checked, that's in fact the line number PHP provides in such a case. I agree this isn't ideal, but that's how PHP works.

**Comment by carlosas-cmp** [comment]
I see :( Thank you and thanks for the tool!
