### ISSUE TITLE
Compatibility with PHPUnit 9

### ISSUE THREAD

**Issue by X-Coder264** [scheb/tombstone#9]
Currently the latest tagged version is not compatible with PHPUnit 9.

I've seen https://github.com/scheb/tombstone/commit/466d043487d17cae7d7588db95c1702478b4b568 that fixes this. When can we expect the next release to be tagged? Thanks for the great package.

**Comment by scheb** [comment]
I'm at the moment in the process of wrapping-up a 1.0 release, which will have support for PHPUnit9 and its dependencies.

If everything goes well, a new release can be expected next week, latest the week after.

**Comment by X-Coder264** [comment]
Thanks for the quick response.

**Comment by scheb** [comment]
@X-Coder264 Released :)

**Comment by X-Coder264** [comment]
@scheb Thank you :)
